// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/Nusantara-Muda/scholarship-api/src/business/entity"

	mock "github.com/stretchr/testify/mock"
)

// BankService is an autogenerated mock type for the BankService type
type BankService struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, filter
func (_m *BankService) Fetch(ctx context.Context, filter entity.BankFilter) (entity.BankFeed, error) {
	ret := _m.Called(ctx, filter)

	var r0 entity.BankFeed
	if rf, ok := ret.Get(0).(func(context.Context, entity.BankFilter) entity.BankFeed); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(entity.BankFeed)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.BankFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
