// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/Nusantara-Muda/scholarship-api/src/business/entity"

	mock "github.com/stretchr/testify/mock"
)

// BankTransferRepository is an autogenerated mock type for the BankTransferRepository type
type BankTransferRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *BankTransferRepository) Get(ctx context.Context) (entity.BankTransfer, error) {
	ret := _m.Called(ctx)

	var r0 entity.BankTransfer
	if rf, ok := ret.Get(0).(func(context.Context) entity.BankTransfer); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entity.BankTransfer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
