// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// BankTransferRepository is an autogenerated mock type for the BankTransferRepository type
type BankTransferRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *BankTransferRepository) Get(ctx context.Context) (scholarship_api.BankTransfer, error) {
	ret := _m.Called(ctx)

	var r0 scholarship_api.BankTransfer
	if rf, ok := ret.Get(0).(func(context.Context) scholarship_api.BankTransfer); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(scholarship_api.BankTransfer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
