// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// BankTransferRepository is an autogenerated mock type for the BankTransferRepository type
type BankTransferRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *BankTransferRepository) Get() scholarship_api.BankTransfer {
	ret := _m.Called()

	var r0 scholarship_api.BankTransfer
	if rf, ok := ret.Get(0).(func() scholarship_api.BankTransfer); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(scholarship_api.BankTransfer)
	}

	return r0
}
