// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// CountryRepository is an autogenerated mock type for the CountryRepository type
type CountryRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, filter
func (_m *CountryRepository) Fetch(ctx context.Context, filter scholarship_api.CountryFilter) ([]scholarship_api.Country, string, error) {
	ret := _m.Called(ctx, filter)

	var r0 []scholarship_api.Country
	if rf, ok := ret.Get(0).(func(context.Context, scholarship_api.CountryFilter) []scholarship_api.Country); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scholarship_api.Country)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, scholarship_api.CountryFilter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, scholarship_api.CountryFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
