// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// DegreeRepository is an autogenerated mock type for the DegreeRepository type
type DegreeRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx
func (_m *DegreeRepository) Fetch(ctx context.Context) ([]scholarship_api.Degree, error) {
	ret := _m.Called(ctx)

	var r0 []scholarship_api.Degree
	if rf, ok := ret.Get(0).(func(context.Context) []scholarship_api.Degree); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scholarship_api.Degree)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
