// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DegreeService is an autogenerated mock type for the DegreeService type
type DegreeService struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *DegreeService) Get() []*string {
	ret := _m.Called()

	var r0 []*string
	if rf, ok := ret.Get(0).(func() []*string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*string)
		}
	}

	return r0
}
