// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Nusantara-Muda/scholarship-api/src/business/entity"
	mock "github.com/stretchr/testify/mock"
)

// EthnicService is an autogenerated mock type for the EthnicService type
type EthnicService struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx
func (_m *EthnicService) Fetch(ctx context.Context) ([]entity.Ethnic, error) {
	ret := _m.Called(ctx)

	var r0 []entity.Ethnic
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Ethnic); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ethnic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
