// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	"github.com/Nusantara-Muda/scholarship-api/src/business/entity"
	mock "github.com/stretchr/testify/mock"
)

// JwtHash is an autogenerated mock type for the JwtHash type
type JwtHash struct {
	mock.Mock
}

// Decode provides a mock function with given fields: tokenString, claim
func (_m *JwtHash) Decode(tokenString string, claim *entity.Claim) error {
	ret := _m.Called(tokenString, claim)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *entity.Claim) error); ok {
		r0 = rf(tokenString, claim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encode provides a mock function with given fields: user
func (_m *JwtHash) Encode(user entity.User) (string, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(entity.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
