// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// MajorService is an autogenerated mock type for the MajorService type
type MajorService struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, filter
func (_m *MajorService) Fetch(ctx context.Context, filter scholarship_api.MajorFilter) (scholarship_api.MajorFeed, error) {
	ret := _m.Called(ctx, filter)

	var r0 scholarship_api.MajorFeed
	if rf, ok := ret.Get(0).(func(context.Context, scholarship_api.MajorFilter) scholarship_api.MajorFeed); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(scholarship_api.MajorFeed)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, scholarship_api.MajorFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
