// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/Nusantara-Muda/scholarship-api/src/business/entity"

	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// SubmitTransfer provides a mock function with given fields: ctx, payment
func (_m *PaymentService) SubmitTransfer(ctx context.Context, payment entity.Payment) (entity.Payment, error) {
	ret := _m.Called(ctx, payment)

	var r0 entity.Payment
	if rf, ok := ret.Get(0).(func(context.Context, entity.Payment) entity.Payment); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(entity.Payment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
