// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RequirementDescriptionRepository is an autogenerated mock type for the RequirementDescriptionRepository type
type RequirementDescriptionRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, scholarshipIDs
func (_m *RequirementDescriptionRepository) Fetch(ctx context.Context, scholarshipIDs []int64) (map[int64][]string, error) {
	ret := _m.Called(ctx, scholarshipIDs)

	var r0 map[int64][]string
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64][]string); ok {
		r0 = rf(ctx, scholarshipIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, scholarshipIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
