// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	scholarship_api "github.com/Nusantara-Muda/scholarship-api"
	mock "github.com/stretchr/testify/mock"
)

// ScholarshipRepository is an autogenerated mock type for the ScholarshipRepository type
type ScholarshipRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, scholarship
func (_m *ScholarshipRepository) Create(ctx context.Context, scholarship scholarship_api.Scholarship) (scholarship_api.Scholarship, error) {
	ret := _m.Called(ctx, scholarship)

	var r0 scholarship_api.Scholarship
	if rf, ok := ret.Get(0).(func(context.Context, scholarship_api.Scholarship) scholarship_api.Scholarship); ok {
		r0 = rf(ctx, scholarship)
	} else {
		r0 = ret.Get(0).(scholarship_api.Scholarship)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, scholarship_api.Scholarship) error); ok {
		r1 = rf(ctx, scholarship)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
